### ISSUE TITLE
issue with nested query

### ISSUE THREAD

**Issue by locnguyenx** [shendepu/moqui-graphql#1]
Your graphql addon for Moqui is very useful in replacement of existing Moqui entity REST api to query data.
It works well for my case, only a exception is in using of nested query. For example: 
`query {moqui{basic{enums{...}}}}` return null

Other 1-level type, i.e `users`, works normal.

In your demo project (https://github.com/shendepu/moqui-graphql-demo), it doesn't work too.

**Comment by shendepu** [comment]
for field which is only placeholder like `basic`
```
        <field name="basic" type="BasicObjectType"/>
```
it was adding a empty-fetcher by default, but was removed since there is need that data fetcher (service) return all nested data for nested object type. 

So you need to make the placeholder field with `empty-fetcher`
```
        <field name="basic" type="BasicObjectType">
            <empty-fetcher/>
        </field>
```

**Comment by locnguyenx** [comment]
It works perfectly.
Many thanks, Jimmy, for your very quick response and this useful addon.
