### ISSUE TITLE
[Question] Support param with List type

### ISSUE THREAD

**Issue by locnguyenx** [shendepu/moqui-graphql#3]
1. As I understood, to query a list of entity value of the same Entity which a param is in a list of values, we can put multiple queries and GraphQL addon will merge into a batch data fetcher. Isn't it?

2. I'd like to call a service with have input param as a List. However, error occurs during initialize GraphQL:
`java.lang.IllegalArgumentException: Parameter zzz type List can't be mapped`
I checked the code and find that List type is not mapped yet in GraphQLSchemaDefinition.
Is there a way to do it in current GraphQL addon?

**Comment by shendepu** [comment]
### To question 1: 
There are three cases in terms of batching query when resolving nested field from list

```
query {
  parties {
    partyType {   // one relationship #A
      description
    }
    contents ( pagination: ...) {  // many which result in list #B
      edges {
        ...
      }
      pageInfo {
        pageIndex
      }
    }
    badges: (pagination: { pageNotLimit: true } ) { // return all results, no pagination #C
      ...
    }
  }
}
```

for case A and C, they are batched to run, while B is not, since it is seems impossible to return multiple pagination query in one SQL.  B will run `entity-find` on PartyContent multiple times, so performance may hurt a little bit.

And they are invisible to users.

### To question 2

Below service is what I used now for mutation. 

```
    <service verb="store" noun="ServiceJobAndParameters">
        <implements service="graphql.GraphQLServices.return#Id"/>
        <in-parameters>
            <auto-parameters entity-name="moqui.service.job.ServiceJob" include="all"/>
            <parameter name="jobName" required="true"/>
            <parameter name="fromDate" default="ec.user.nowTimestamp"/>
            <parameter name="thruDate" default="null"/>
            <parameter name="paused" default-value="N"/>
            <parameter name="parameters" type="List" default="[]"><parameter name="parameter" type="Map">
                <parameter name="parameterName" required="true"/>
                <parameter name="parameterValue" required="true"/>
            </parameter></parameter>
        </in-parameters>
        <out-parameters>
            <auto-parameters entity-name="moqui.service.job.ServiceJob" include="all"/>
        </out-parameters>
        <actions>
            <service-call name="store#moqui.service.job.ServiceJob" in-map="context" out-map="context"/>

            <entity-find-one entity-name="moqui.service.job.ServiceJob" value-field="serviceJob"/>
            <service-call name="graphql.GraphQLServices.put#ContextWithId" in-map="[ev: serviceJob]" out-map="context"/>
        </actions>
    </service>
```

#### NOTE:

You must define the parameter with `List`, the nested a parameter which is `Map` whose keys must be defined inside. This is important so that `moqui-graphql` can build GraphQL input object.

```
<parameter name="parameters" type="List" default="[]"><parameter name="parameter" type="Map">
  <parameter name="parameterName" required="true"/>
  <parameter name="parameterValue" required="true"/>
</parameter></parameter>
```

**Comment by locnguyenx** [comment]
For question 2, I've just tried your solution and found that it only works if field definition have property `for="mutation"`. My service is for query info only (need to have more processing so can't use entity fetcher)

**Comment by shendepu** [comment]
You may notice for query which results in list the argument type is `OperationInputType`, `DateRangeInputType` or `PaginationInputType`.

You can use `service-fetcher` for query which underlying service defines in parameter with type 

- `com.moqui.graphql.OperationInputType`
- `com.moqui.graphql.DateRangeInputType`
- `com.moqui.graphql.PaginationInputType`

e.g. 

```
<service verb="find" noun="EmplPositionFT">
        <implements service="graphql.GraphQLServices.return#Connection"/>
        <in-parameters>
            <parameter name="emplPositionId" type="com.moqui.graphql.OperationInputType"/>
            <parameter name="periodValid_" type="Boolean"/>
            <parameter name="title" type="com.moqui.graphql.OperationInputType"/>
            <parameter name="fullTimeFlag" type="com.moqui.graphql.OperationInputType"/>
            <parameter name="virtualFlag" type="com.moqui.graphql.OperationInputType"/>
            <parameter name="statusId" type="com.moqui.graphql.OperationInputType"/>
        </in-parameters>
</service>
```

**Comment by locnguyenx** [comment]
I need a in-parameter with List type, as in your sample mutation service.

It works if I put a property `for="mutation"` in field definition, but it not make sense because my service is just for query.

**Comment by shendepu** [comment]
@locnguyenx I have made commit 8039fefc62e383e35d2579c20d99a4b1ffb07f56 to support list and map nested input data structure for query field just like for mutation. You have a try, and let me know if you encounter any issue.

**Comment by locnguyenx** [comment]
Has retested the query with List type in-param. This update works as expected. Thanks a lot.
