### ISSUE TITLE
[upgrade] Moqui Framework private method

### ISSUE THREAD

**Issue by dhcdata** [shendepu/moqui-graphql#4]
This moqui-framework [commit](https://github.com/moqui/moqui-framework/commit/a75f1d26440821dc1f8ed335fa74146c6f8887d8) made the `populateFieldTreeAndAliasPathMap` method private.  The signature had been changed a couple weeks before that.

This is a breaking change for this project.

**Comment by shendepu** [comment]
Thanks for reporting this. I've noticed this break change in this morning, It is not just private method change, the fieldPath also adds expression support.  I have been working on the fix. It should be fixed within one or two days.

**Comment by jonesde** [comment]
Let me know if you need any of these methods to be public. Method signatures have changed, especially for the internally used methods in that class... and aside from a very few none of these are meant to be used external to the class but certainly could be so let me know if you need something or other.

**Comment by shendepu** [comment]
@jonesde I need to use `EntityDataDocument.populateFieldTreeAndAliasPathMap()` to generate the fieldTree and fieldAliasPathMap. If it is public, I can reuse it, otherwise, I need to copy the code out and still need to main it exactly same. 

I made a PR https://github.com/moqui/moqui-framework/pull/232 on this.

**Comment by shendepu** [comment]
@dhcdata I made the commit f6014db to support the multiple field alias in data document. It still relies on `DataDocument.populateDataDocRelatedMap`. A PR https://github.com/moqui/moqui-framework/pull/232 is made.

**Comment by shendepu** [comment]
The PR to moqui-framework has been merged. So I close this issue.
